[package]
name = "album-club-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.10"
google-sheets4 = "3.0.0"
tokio = {version = "1", features = ["rt-multi-thread"]}
